pipeline {
  agent any

 tools {
        maven 'maven'
    }
  stages {
    stage('Checkout Application Git Branch') {
        steps {
            git url: 'https://github.com/seunghyejeong/gitops-repository.git', branch: 'main'
        }
        post {
                failure {
                  echo 'Failed to clone repository'
                }
                success {
                  echo 'Repository cloned successfully'
                }
        }
    }
    stage('Maven Jar Build') {
        steps {
            sh 'mvn -f /var/jenkins_home/workspace/git-maven/edu-msa-ui-master/pom.xml clean package'
        }
        post {
                failure {
                  echo 'Failed to build Maven'
                }
                success {
                  echo 'Maven war built successfully!'
                }
        }
    }
  }
}
