def version = '1.0'
version = String.format("%.1f", (version as Double) + 0.1)

pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/jeongbami/gitops-repository.git', branch: 'main'
      }
    }

    stage('Build Docker Image') {
      steps {
            try {
                docker.build('seunghyejeong/build-maven:1.1', '-f Dockerfile .')
                withCredentials([usernamePassword(credentialsId: 'seunghyejeong', passwordVariable: 'tlqkfak0315!', usernameVariable: 'seunghyejeong')]) {
                    def image = docker.build("seunghyejeong/project:${version}")
                    docker.withRegistry('https://index.docker.io/v1/', 'seunghyejeong') {
                        image.push()
                    }
                }
            } catch (Exception ex) {
                println "Error: ${ex.getMessage()}"
                currentBuild.result = 'FAILURE'
            }
          }
        }
      }
    }
  }
}
