apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-user
  labels:
    app: user-msa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-msa
  template:
    metadata:
      labels:
        app: user-msa
    spec:
      containers:
      - name: user-msa
        image: ${IMAGE_REGISTRY_URL}:5001/${DIRECTORY_NAME}/${IMAGE_NAME}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28084      
      imagePullSecrets:
         - name: edu-msa-secret        
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-user
  labels:
    app: user-msa  
spec:
  ports:
  - nodePort: ${EDU_MSA_USER}
    port: 28084
    protocol: TCP
    targetPort: 28084
  selector:
    app: user-msa
  type: NodePort
