 pipeline { 
    environment { 
        repository = "seunghyejeong/project"  
        DOCKERHUB_CREDENTIALS = credentials('docker-token')
        dockerImage = '' 
  }
  agent any 
  stages { 
      stage('Building our image') { 
          steps { 
              script { 
                  sh "cp /var/jenkins_home/workspace/git-maven/edu-msa-ui-master/target/edu-msa-ui-1.0.0.war /var/jenkins_home/workspace/docker-build-deploy/docker"
                  dockerImage = docker.build repository + ":$BUILD_NUMBER" 
              }
          } 
      }
      stage('Login'){
          steps{
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
          }
      }
      stage('Deploy our image') { 
          steps { 
              script {
                sh 'docker push $repository:$BUILD_NUMBER'
              } 
          }
      } 
      stage('Cleaning up') { 
      steps { 
              sh "docker rmi $repository:$BUILD_NUMBER"
          }
      } 
  }
}
